export const PRICE_PLANS = [
  {
    id: "studio",
    icon: "MapPin",
    label: "STUDIO SESSION",
    title: "據點體驗",
    subtitle: "心見大安 · 北投老爺酒店",
    price: 2000,
    unit: "元",
    duration: "60 分鐘",
    tagline: "走進靜謐容器，讓身體與外界節奏徹底斷開",
    includes: [
      "約 10 分鐘初次晤談",
      "60 分鐘顱薦椎 / 內臟筋膜工作",
      "體驗後靜置與回饋交流",
      "獨立靜謐的工作空間",
      "無需攜帶任何設備",
    ],
    locations: [
      {
        name: "心見大安",
        address: "台北市大安區和平東路二段 100 號 3 樓之 8",
        note: "捷運文湖線大安站步行約 5 分鐘",
      },
      {
        name: "北投老爺酒店 × 心見",
        address: "台北市北投區中和街 2 號 11 樓",
        note: "溫泉山林環境，需預約",
      },
    ],
    accentColor: "primary",
    featured: false,
  },
  {
    id: "home",
    icon: "Home",
    label: "HOME VISIT",
    title: "到府服務",
    subtitle: "台北市 · 新北市全區",
    price: 2500,
    unit: "元",
    duration: "60 分鐘",
    tagline: "在最熟悉的地方放鬆，體驗後直接躺著休息",
    includes: [
      "約 10 分鐘初次晤談",
      "60 分鐘顱薦椎 / 內臟筋膜工作",
      "工作者攜帶所有設備到府",
      "體驗後靜置與回饋交流",
      "台北市、新北市全區服務",
    ],
    idealFor: [
      "有嬰幼兒陪伴的家長",
      "行動不便或需要隱私的來訪者",
      "孕婦（需先取得婦產科醫師同意，體驗後可直接休息）",
      "不想通勤的忙碌族群",
    ],
    note: "偏遠地區酌收交通費，預約時事先告知",
    accentColor: "accent",
    featured: true,
  },
];

export const COMPARISON_TABLE = {
  title: "心見據點 vs 到府 vs 一般按摩店：完整比較",
  updatedAt: "2026年 雙北地區行情參考",
  dimensions: [
    {
      label: "費用",
      studio: "2,000 元 / 60 分鐘（自費）",
      home: "2,500 元 / 60 分鐘（自費）",
      massage: "800–1,500 元 / 60 分鐘（自費）",
    },
    {
      label: "工作時間",
      studio: "60 分鐘 全程一對一",
      home: "60 分鐘 工作者到府",
      massage: "60 分鐘，力道較重",
    },
    {
      label: "核心手法",
      studio: "顱薦椎（5g 力道）+ 內臟筋膜放鬆",
      home: "顱薦椎（5g 力道）+ 內臟筋膜放鬆",
      massage: "瑞典式、深層肌肉按摩",
    },
    {
      label: "適合族群",
      studio: "想有儀式感、深度放鬆的都市人",
      home: "嬰幼兒、孕婦、行動不便者",
      massage: "肌肉緊繃、短期放鬆需求",
    },
    {
      label: "穿著",
      studio: "全程穿著自己的衣物",
      home: "全程穿著自己的衣物",
      massage: "依店家而定",
    },
    {
      label: "力道",
      studio: "極輕（約 5 公克），無痛",
      home: "極輕（約 5 公克），無痛",
      massage: "中重，可能有酸痛感",
    },
  ],
  sources: ["心見大安", "心見到府", "一般按摩店"],
};
